# Site settings
title: Vincent Phan 
description: From Actuary to Data Science
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vincent Phan
user_description: Actuarial Data Scientist.
user_title: Actuarial Data Scientist
email: vincentphan3004@gmail.com
twitter_username: lorem_ipsum
github_username:  vincentphan3004
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
